# Generated by Django 5.1.4 on 2025-01-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0002_alter_chatmessage_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='room_name',
            new_name='name',
        ),
    ]
