# Generated by Django 5.1.4 on 2025-01-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced')], default='basic', max_length=20),
        ),
    ]
