# Generated by Django 5.1.4 on 2025-01-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0002_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='game',
        ),
    ]
