# Generated by Django 5.1.4 on 2025-01-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0003_remove_gameplayer_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
