# Generated by Django 5.1.4 on 2025-01-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
